### ISSUE TITLE
Google fonts、AdobeTypekitのWebフォントが読み込まれていない

### ISSUE THREAD

**Issue by sugiosugio** [pannpers/hitocoto#13]
CSSで指定されているWebフォントが表示されていないが、読み込みjsの不具合？

**Comment by pannpers** [comment]
https://github.com/pannpers/hitocoto/pull/8#discussion_r387510019

**Comment by sugiosugio** [comment]
function.js内で読み込んでいます〜。

(function(d) {
var config = {
  kitId: 'pkq3glp',
  scriptTimeout: 3000,
  async: true
},

ただPVの上限などもあり、AdobeTypekitフォントの使用はやめようかなと検討中です。。

**Comment by sugiosugio** [comment]
Adobe Fonts（AdobeTypekitから名称変更してました！）ですが、PV数の上限ないようなので、やはり使用する方向で進めたいと思います！下記スクリプトをhead内に読み込むような形に修正お願いできますでしょうか〜。

<script>
  (function(d) {
    var config = {
      kitId: 'pkq3glp',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>

**Comment by pannpers** [comment]
@sugiosugio Noto Sansのフォントがレンダリングされていない原因が分かりました！以前のこちらのCommit↓↓でスギオさんが行ってくれた `style.css` への修正が `styles.css`には反映されていなかったからでした。（つまりそもそも `font-family` の指定自体がなかったと・・・ｗ）
https://github.com/pannpers/hitocoto/commit/7a90aa0d60d74e7425f7ac5c18d5e25ab91dd9a5

**Comment by pannpers** [comment]
Adobe Fontsと併せて、有効にするように修正しました！お手すきの際に↓↓こちらご確認お願いします〜
https://github.com/pannpers/hitocoto/pull/19/files

**Comment by sugiosugio** [comment]
AdobeFonts読み込み、ローカルテスト環境にてGit反映確認しました〜。

>Noto Sansのフォントがレンダリングされていない原因が分かりました！以前のこちらのCommit↓↓でスギオさんが行ってくれた style.css への修正が styles.cssには反映されていなかったからでした。（つまりそもそも font-family の指定自体がなかったと・・・ｗ）

こちらお伝えしておらずすみません、AdobeFontsを使用することに伴い、GoogleのNotoSansは使用しないことにまして、font-family指定を変更していました。。

font-family:"YakuHanJP","Noto Sans JP", sans-serif;
↓
font-family:"YakuHanJP","游ゴシック","YuGothic", "ヒラギノ角ゴ Pro", "Hiragino Kaku Gothic Pro", "メイリオ", "Meiryo", sans-serif;

今後もGoogleフォントは使用しないため、下記のの読み込み記述は何処かのタイミングで削除していただいて大丈夫かと思います〜。すみません、お手数おかけします！

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,500,700&display=swap">

**Comment by pannpers** [comment]
@sugiosugio 了解です！↓↓ここの行を消すだけなので、次に修正するタイミングで消しておきます！ `font-family` の方はスギオさんの方で 最新の masterブランチを `git pull` して、修正して頂ければと思います〜
https://github.com/pannpers/hitocoto/blob/master/index.ejs#L9
