### ISSUE TITLE
hitocoto一覧ページ（Archive）のCSS不具合

### ISSUE THREAD

**Issue by sugiosugio** [pannpers/hitocoto#14]
hitocoto一覧ページ（Archive）の動画一覧部分の表示がHTML時と表示が異なる。
@media screen and (min-width: 769px)の#archiveList li が効いていない？

**Comment by pannpers** [comment]
@sugiosugio HTMLのタグがちょっとおかしくなっていたので、修正いたしました！↓↓
https://github.com/pannpers/hitocoto/pull/20/files
