### ISSUE TITLE
録音画面でのRecボタンのテキスト表示についての修正要望

### ISSUE THREAD

**Issue by sugiosugio** [pannpers/hitocoto#17]
録音画面でのRecボタン上のテキスト表示（140秒以内でhitocoto!）ですが、
タイトル未入力状態ではテキストは非表示ですので、修正お願いします。
※ダミーで入っているhogeもいったん無しにしてもらってもいいかもしれませんー

【タイトル未入力】
p#txtRec span {
    opacity: 0;
    transition: 0.75s;
    letter-spacing: 0.25em;
    transition-property: letter-spacing;
}
↓
【タイトル入力済み】
p#txtRec.statusRecStb span, p#txtRec.statusRecNow span {
    opacity: 1;
    letter-spacing: 0.05em;
}

**Comment by pannpers** [comment]
> - タイトル未入力状態ではテキストは非表示ですので、修正お願いします。
- ※ダミーで入っているhogeもいったん無しにしてもらってもいいかもしれませんー

@sugiosugio 上記2点修正いたしました！
